###
POST http://localhost:8080/status
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174001",
  "nombre": "Activo",
  "fecha": "2025-05-28"
}

###
GET http://localhost:8080/status

###
GET http://localhost:8080/status/buscar?nombre=Activo

###
DELETE http://localhost:8080/status/eliminar?nombre=Activo
